[package]
name = "roguelike-tutorial"
version = "0.1.0"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
edition = "2018"
license = "WTFPL"
readme = "README"

[dependencies]
tcod = { version = "0.15", features = ["serialization"] }
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
